# Generated by Django 4.2.25 on 2025-11-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemKeranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('keranjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Ecommerce.keranjang')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat_pengiriman', models.TextField()),
                ('metode_pembayaran', models.CharField(choices=[('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('cod', 'Bayar di Tempat')], max_length=50)),
                ('tanggal_checkout', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibayar', models.BooleanField(default=False)),
                ('keranjang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.keranjang')),
            ],
        ),
    ]
