# Generated by Django 4.2.25 on 2025-11-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='gambar',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='alamat_pengiriman',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='metode_pembayaran',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='sudah_dibayar',
        ),
        migrations.RemoveField(
            model_name='keranjang',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(default='no description available'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
