# Generated by Django 5.2.8 on 2025-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_keranjang_user_alter_checkout_keranjang'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produk',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
