# Generated by Django 5.2.8 on 2025-11-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_produk_rating_produk_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='keranjang',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
