# Generated by Django 5.2.8 on 2025-11-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_keranjang_is_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('transfer', 'Bank Transfer')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_method',
            field=models.CharField(choices=[('regular', 'Regular'), ('express', 'Express')], default='regular', max_length=20),
        ),
    ]
